In [1]:
# Читаем текстовый файл
with open('sentences.txt', 'r') as f:
    sentences = f.readlines()

In [2]:
sentences[0]

'In comparison to dogs, cats have not undergone major changes during the domestication process.\r\n'

In [3]:
# Переводим строки в нижний регистр
sentences = [sentence.lower() for sentence in sentences]

In [4]:
sentences[0]

'in comparison to dogs, cats have not undergone major changes during the domestication process.\r\n'

In [5]:
# Разбиваем предложения на слова
import re

sentences = [re.split('[^a-z]', sentence) for sentence in sentences]

In [6]:
sentences[0]

['in',
 'comparison',
 'to',
 'dogs',
 '',
 'cats',
 'have',
 'not',
 'undergone',
 'major',
 'changes',
 'during',
 'the',
 'domestication',
 'process',
 '',
 '',
 '']

In [7]:
# удаляем пустые слова
sentences = [[word for word in sentence if len(word)>0] for sentence in sentences]

In [8]:
sentences[0]

['in',
 'comparison',
 'to',
 'dogs',
 'cats',
 'have',
 'not',
 'undergone',
 'major',
 'changes',
 'during',
 'the',
 'domestication',
 'process']

In [9]:
# Составляем словарь уникальных слов
# Ключ -- само слово, значение -- его порядковый номер в порядке появления
words = {}
counter = (x for x in range(10**3))

_ = [words.update({word: counter.next()}) for sentence in sentences for word in sentence if word not in words]

In [10]:
print words['cats']
print words['dogs']
print words['domestication']
print words['count']

4
3
12
253


In [11]:
# Составляем матрицу признаков
import numpy as np

feature_mat = np.array([[sentence.count(word) for word in words] for sentence in sentences])

In [12]:
print feature_mat
print feature_mat.shape

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
(22, 254)


In [13]:
# Вычисляем косинусное расстояние до предложения 0
import scipy.spatial as ss

distances = [ss.distance.cosine(feature_mat[0], feature) for feature in feature_mat]

In [14]:
distances

[0.0,
 0.9527544408738466,
 0.8644738145642124,
 0.8951715163278082,
 0.7770887149698589,
 0.9402385695332803,
 0.7327387580875756,
 0.9258750683338899,
 0.8842724875284311,
 0.9055088817476932,
 0.8328165362273942,
 0.8804771390665607,
 0.8396432548525454,
 0.8703592552895671,
 0.8740118423302576,
 0.9442721787424647,
 0.8406361854220809,
 0.956644501523794,
 0.9442721787424647,
 0.8885443574849294,
 0.8427572744917122,
 0.8250364469440588]

In [15]:
# Находим два первых минимума и выводим ответ
min1 = 1.
min2 = 1.
idx1 = 1
idx2 = 1

for i, x in enumerate(distances[1:]):
    if x <= min1:
        min2 = min1
        idx2 = idx1
        min1 = x
        idx1 = i+1
    elif x < min2:
        min2 = x
        idx2 = i+1

print 'Первое ближайшее предложение: {0} ({1:.3})'.format(idx1, min1)
print 'Второе ближайшее предложение: {0} ({1:.3})'.format(idx2, min2)

Первое ближайшее предложение: 6 (0.733)
Второе ближайшее предложение: 4 (0.777)
